#:kivy 1.0.9
<ScreenManager>:
	GameScreen:
	SettingsScreen:

<GameScreen>:
    BoxLayout:
        Button:
            text: 'Settings Screen'
            on_press: root.manager.current = 'SettingsScreen'

        Button:
            text: 'Game'

<SettingsScreen>:
    BoxLayout:
        Button:
            text: 'Settings'
        Button:
            text: 'Game'
            on_press: root.manager.current = 'GameScreen'

